### ISSUE TITLE
DMP 2024

### ISSUE THREAD

**Issue by Oky-period-tracker** [Oky-period-tracker/periodtracker#65]
### **Description**
This project will enable Oky code to be run on other operating systems including Windows and Linux. Currently, the code only runs on Mac and we would like to ensure the code can also be deployed using Windows and Linux. 

### **Goals**
1. The code can be setup and deployed from a laptop which runs on Windows or Linux
2. Clear documentation is created so that anyone can easily deploy the code from their machine and setup the environment correctly. 
3. The code can still be run on Mac without any issues
4. The Content Management system (CMS), the mobile apps (android and iOS) and the backend run well independently of the operating system used to deploy it. 
5. The setup for the code is not complicated and fairly similar regardless of operating system

### **Expected Outcome**

- [ ] Any developer can setup their environment and deploy the code for:

- backend (APIs and database)
- mobile apps (android and iOS)
- Content Management System (CMS)
without any issues or errors. 

- [ ] Code setup for operating systems which is not Mac is well documented, including software dependencies and respective versions of these. 
- [ ] Commands are created to simplify setup process

### **Acceptance criteria**

- The code can be run using Windows and Linux operating systems and all the components in the project (mobile apps, CMS and backend) work the same as when deploying them from Mac. 

- The environment setup and code deployment is clearly documented including all the software dependencies required.  

### **Mockups / Wireframes**
None but the apps, cms, backend should run like it currently does when deploying from mac

Product Name
Oky

Project Name
Enabling Oky code to run on Windows and Linux computers

Organization Name:
Unicef

Domain
okyapp.info

Tech Skills Needed:
React Native, Node, Typescript, Postgres

Mentor(s)

Complexity
High

Category

Sub Category

**Comment by lalbelda** [comment]
closed

**Comment by shambhabya** [comment]
Hello, I am interested in this project, can you help me how to get started.
